name: Hide Sensitive Information
on: push
jobs:
  print-secret-token:
    runs-on: ubuntu-latest
    steps:
      - name: Echo my seccret
        run: echo "your secret token is ${{ secrets.API_THEMOVIEDB }}"
