name: Hide Sensitive Information
on: push
jobs:
  print-secret-token:
    runs-on: ubuntu-latest
    env:
      API_THEMOVIEDB: ${{ secrets.API_THEMOVIEDB }}
    steps:
      - name: Print Secret Token
        run: echo $API_THEMOVIEDB
